### PR TITLE
Created scraper for updated MWRD site

### PR DESCRIPTION
**Pull request by pjsier**
The data on the new site is in a slightly different format with a bit more information, so the scraper outputs to two csvs: one with the data as it is on MWRD's site, and another that tries to match the format currently on the repo.

The `segment` column doesn't totally line up, mainly because of segments 10, 11, 30, 31, and 32. I took a look at the map to see which locations in the updated format matched some segments, but I couldn't find any examples in the new or old data for segment 10, and none in the new data for segment 32. Some of the columns might need to be changed around, and I'm happy to make any changes!

### CODE REVIEW

**Comment by derekeder** [comment]
@pjsier cool! thanks for this. it's great to have an updated version of the scraper going.

The old one wrote the output to a sqlite database, and I see you're doing CSV. CSV might be easier for people to work with, but for the website to use it, we'll need the data also in sqlite

**Comment by pjsier** [comment]
@derekeder Gotcha, that makes sense. Would you want it to write to the current database, or to a separate SQLite file?

**Comment by derekeder** [comment]
If we can continue to reuse the same database, that would be ideal so we don't have to rewrite any of the server-side code.

**Comment by pjsier** [comment]
@derekeder This should work! I only added events after the last recorded CSO on the current app (5/14/16) even though the updated format has earlier events. It seemed better than having to decide which ones to overwrite for now at least

**Comment by derekeder** [comment]
@pjsier rad!

Could you add documentation on how to run the scraper? The old one @sbeslow wrote took in a start and end date. Might be a good idea to support that too. Also, it would be good to be able to delete everything and re-scrape the entire history if we wanted to.

**Comment by pjsier** [comment]
Good call on the documentation, I added a README and updated it to use `argparse` which should make setting dates a bit easier. Other than that, I added a `replace_overlap()` function which scrapes the site, finds the earliest date, drops any dates that overlap, and inserts all the scraped data like you mentioned. They only have as far back as April 2016 currently, but in case that changes it's there. Let me know if there's anything else!

**Comment by derekeder** [comment]
@pjsier this looks great! I'll merge and try it out!

**Pull request merged**
